Repository sds/haml-lint, pull requests merged in 2024-02, with the labels that each got.

#487 Fix tag attribute spacing
  CHANGELOG.md
  lib/haml_lint/ruby_extraction/chunk_extractor.rb
  lib/haml_lint/spec/shared_rubocop_autocorrect_context.rb
  lib/haml_lint/utils.rb
  spec/haml_lint/linter/rubocop_autocorrect_examples/blank_lines_examples.txt
  spec/haml_lint/linter/rubocop_autocorrect_examples/changing_indentation_examples.txt
  spec/haml_lint/linter/rubocop_autocorrect_examples/interpolation_examples.txt
  spec/haml_lint/linter/rubocop_autocorrect_examples/multibyte_chars_examples.txt
  spec/haml_lint/linter/rubocop_autocorrect_examples/multiline_examples.txt
  spec/haml_lint/linter/rubocop_autocorrect_examples/ruby_filter_examples.txt
  spec/haml_lint/linter/rubocop_autocorrect_examples/script_examples.txt
  spec/haml_lint/linter/rubocop_autocorrect_examples/tag_attributes_examples.txt
  spec/haml_lint/linter/rubocop_autocorrect_examples/tag_complex_examples.txt
  spec/haml_lint/linter/rubocop_autocorrect_examples/tag_nesting_examples.txt
  spec/haml_lint/linter/rubocop_autocorrect_examples/tag_script_examples.txt
  spec/haml_lint/linter/rubocop_autocorrect_examples_spec.rb
  spec/haml_lint/linter/rubocop_spec.rb
  spec/haml_lint/ruby_extraction/chunk_extractor_spec.rb
Labels: bug

#494 Feature: introduce RuboCop performance
  .rubocop.yml
  Appraisals
  Gemfile
  gemfiles/haml5.0.gemfile
  gemfiles/haml5.1.gemfile
  gemfiles/haml5.2.gemfile
  gemfiles/haml6.0.gemfile
  gemfiles/haml6.1.gemfile
  gemfiles/haml6.2.gemfile
  gemfiles/haml6.3.gemfile
  gemfiles/rubocop1.0.gemfile
  lib/haml_lint/linter.rb
  lib/haml_lint/linter/empty_script.rb
  lib/haml_lint/linter/id_names.rb
  lib/haml_lint/linter/indentation.rb
  lib/haml_lint/linter/leading_comment_space.rb
  lib/haml_lint/linter/space_inside_hash_attributes.rb
  lib/haml_lint/linter/tag_name.rb
  lib/haml_lint/linter/trailing_whitespace.rb
  lib/haml_lint/linter/unnecessary_string_output.rb
  lib/haml_lint/ruby_extraction/chunk_extractor.rb
  lib/haml_lint/ruby_extraction/non_ruby_filter_chunk.rb
  lib/haml_lint/ruby_extraction/ruby_filter_chunk.rb
  lib/haml_lint/ruby_extraction/script_chunk.rb
  lib/haml_lint/spec/shared_rubocop_autocorrect_context.rb
  spec/haml_lint/tree/haml_comment_node_spec.rb
  spec/support/examples_parsing_helpers.rb
Labels: enhancement, contributions-welcome

#497 Update README.md to reflect presence of --stdin
  README.md
Labels: documentation
